config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:sessions],
    controllers: { registrations: 'users/registrations' }

  as :user do
    get 'login' => 'devise/sessions#new', as: :new_user_session
    post 'login' => 'devise/sessions#create', as: :user_session
    delete 'logout' => 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :teams do
    resources :members
  end

  get 'invitations/:id' => 'invitations#accept', as: :accept_invitation

  root to: 'teams#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  scope :not, -> (*records) { where.not(id: records.flatten.map(&:id)) }
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  TOKEN_LENGTH = 48

  belongs_to :member
  belongs_to :sender, class_name: 'Member'
  has_one :team, through: :member

  before_validation :generate_token

  validates :email, presence: true, format: { with: User.email_regexp }
  validates :token,
    presence: true,
    uniqueness: true,
    format: { with: /\A[0-9a-f]{#{TOKEN_LENGTH}}\z/ }

  def to_param
    token
  end

  private

  def generate_token
    while token.blank? || Invitation.where(token: token).not(self).exists?
      self.token = SecureRandom.hex(TOKEN_LENGTH / 2)
    end
  end
end

app/models/member.rb
class Member < ApplicationRecord
  acts_as_url :name, url_attribute: :slug, scope: :team_id, limit: 64

  belongs_to :team, counter_cache: true
  belongs_to :user
  has_many :invitations

  validates :name, :team, presence: true
  validates :name, uniqueness: { scope: :team_id, case_sensitive: false }
  validates :user, presence: true, if: :manager?
  validates :email, format: { with: User.email_regexp, allow_blank: true }

  def to_s
    name
  end

  def to_param
    slug
  end

  def email
    @email || user.try(:email)
  end

  def email?
    !email.blank?
  end

  attr_writer :email
end

app/models/team.rb
class Team < ApplicationRecord
  acts_as_url :name, url_attribute: :slug, limit: 64

  has_many :members

  validates :name, presence: true

  def to_s
    name
  end

  def to_param
    slug
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :members
  has_many :teams, through: :members
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  def after_sign_in_path_for(resource)
    stored_location_for(resource) || super
  end

  def after_sign_up_path_for(resource)
    stored_location_for(resource) || super
  end

  def team
    @team ||= Team.includes(members: :user).find_by(slug: team_id)
  end

  helper_method :team

  def team_id
    params[:team_id]
  end

  def current_member
    @current_member ||= team.members.find_by(user: current_user)
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  before_action :authenticate_user!

  def accept
    invitation.member.update!(user: current_user)
    redirect_to invitation.team, notice: "Welcome to #{invitation.team}!"
  end

  private

  def invitation
    @invitation || Invitation.find_by!(token: params[:id])
  end

  def save_clicked_invitation
    session[:invitation] = invitation.id
  end

  def authenticate_user!
    store_location_for(:user, request.url)
    save_clicked_invitation
    super
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  INVITATION_SLOTS = 5

  def index
  end

  def new
    @members = empty_member_list
  end

  def create
    InviteMembers
      .new(team, current_member, params[:members].values)
      .on(:invited) { |happy, sad| invitations_created(happy, sad) }
      .call
  end

  private

  def member_params
    params.require(:member).permit(:name)
  end

  def success_notice(happy)
    "Added #{happy.count} #{'member'.pluralize(happy.count)}." if happy.any?
  end

  def invitations_created(happy, sad)
    if happy.any? && sad.empty?
      redirect_to team_members_path(team), notice: success_notice(happy)
    else
      @members = sad + empty_member_list(INVITATION_SLOTS - sad.size)
      flash.now[:notice] = success_notice(happy)
      render :new
    end
  end

  def empty_member_list(n = INVITATION_SLOTS)
    (1..n).map { team.members.build }
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def index
  end

  def show
  end

  private

  def team
    @team ||= Team.find_by(slug: params[:id])
  end

  helper_method :team
end

app/controllers/users/registrations_controller.rb
module Users
  class RegistrationsController < Devise::RegistrationsController
    def create
      super do |user|
        confirm_from_viewed_invitations(user, session.delete(:invitation))
      end
    end

    private

    def confirm_from_viewed_invitations(user, id)
      user.confirm if id.present? && Invitation.where(id: id).exists?
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  def user_facing_flashes
    flash.to_hash.slice('alert', 'error', 'notice', 'success')
  end
end

app/views/application/_analytics.html.erb
<% if ENV["SEGMENT_KEY"] %>
  <script type="text/javascript">
    window.analytics=window.analytics||[],window.analytics.methods=["identify","group","track","page","pageview","alias","ready","on","once","off","trackLink","trackForm","trackClick","trackSubmit"],window.analytics.factory=function(t){return function(){var a=Array.prototype.slice.call(arguments);return a.unshift(t),window.analytics.push(a),window.analytics}};for(var i=0;i<window.analytics.methods.length;i++){var key=window.analytics.methods[i];window.analytics[key]=window.analytics.factory(key)}window.analytics.load=function(t){if(!document.getElementById("analytics-js")){var a=document.createElement("script");a.type="text/javascript",a.id="analytics-js",a.async=!0,a.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n)}},window.analytics.SNIPPET_VERSION="2.0.9",
    window.analytics.load("<%= ENV["SEGMENT_KEY"] %>");
    window.analytics.page();
  </script>
<% end %>

app/views/application/_analytics.html.haml
- if ENV["SEGMENT_KEY"]
  :javascript
    window.analytics=window.analytics||[],window.analytics.methods=["identify","group","track","page","pageview","alias","ready","on","once","off","trackLink","trackForm","trackClick","trackSubmit"],window.analytics.factory=function(t){return function(){var a=Array.prototype.slice.call(arguments);return a.unshift(t),window.analytics.push(a),window.analytics}};for(var i=0;i<window.analytics.methods.length;i++){var key=window.analytics.methods[i];window.analytics[key]=window.analytics.factory(key)}window.analytics.load=function(t){if(!document.getElementById("analytics-js")){var a=document.createElement("script");a.type="text/javascript",a.id="analytics-js",a.async=!0,a.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n)}},window.analytics.SNIPPET_VERSION="2.0.9",
    window.analytics.load("#{ENV["SEGMENT_KEY"]}");
    window.analytics.page();

app/views/application/_css_overrides.html.haml
- if Rails.env.test?
  :css
    * {
      transition-property: none !important;
    }

app/views/application/_flashes.html.haml
- if flash.any?
  .flashes
    - user_facing_flashes.each do |key, value|
      %div{:class => "flash-#{key}"}= value

app/views/application/_head.html.haml
%meta{:content => 'text/html; charset=UTF-8', 'http-equiv' => 'Content-Type'}/
%meta{:charset => 'utf-8'}/
%meta{:content => 'NOODP', :name => 'ROBOTS'}/
%meta{:content => 'width=device-width, initial-scale=1, shrink-to-fit=no', :name => 'viewport'}/
%title= title
= stylesheet_link_tag :application, media: 'all', 'data-turbolinks-track': 'reload'
= render 'javascript'
= csrf_meta_tags

app/views/application/_javascript.html.haml
= javascript_include_tag :application, 'data-turbolinks-track' => 'reload'
= render 'analytics'
- if Rails.env.test?
  = javascript_tag do
    $.fx.off = true;
    $.ajaxSetup({ async: false });

app/views/layouts/application.html.haml
!!!
%html{:lang => 'en'}
  %head
    = render 'application/head'
  %body{:class => body_class}
    %nav
      - if signed_in?
        = current_user.email
        = link_to 'Log out', destroy_user_session_path, method: :delete
      - else
        = link_to 'Log in', new_user_session_path
    = render 'flashes'
    = yield
    = yield :javascript
    = render 'css_overrides'

app/views/layouts/devise.html.haml
!!!
%html{:lang => 'en'}
  %head
    = render 'application/head'
  %body{:class => body_class}
    = render 'flashes'
    = yield
    = yield :javascript
    = render 'css_overrides'

app/views/members/_member.html.haml
%li= link_to member

app/views/members/index.html.haml
= link_to 'Add members', new_team_member_path(team)

%ul= render team.members

app/views/members/new.html.haml
= form_tag [team, :members], method: :post do
  %ul
    - @members.each.with_index do |member, i|
      %li
        = simple_fields_for "members[#{i}]", member do |fields|
          = fields.input :name
          = fields.input :email, as: :email
  %button{type: :submit}
    Invite members